### ISSUE TITLE
Release tarball format

### ISSUE THREAD

**Issue by geaaru** [canonical/lxd#12183]
# Required information

 * Distribution: Macaroni OS, Funtoo, Gentoo

# Issue description

Hi, the GitHub Release tarball doesn't contain the libraries raft and dqlite used in the Gentoo and Funtoo ebuilds without the need to have separate packages for these dependencies.

Are there plans to fix this and supply a tarball like was available on the linuxcontainer.org site?

Thanks in advance

**Comment by tomponline** [comment]
Hrm should be the same as usual. Which file did you download the .zip or the .tar.gz?

**Comment by tomponline** [comment]
Ah you need the lxd-*.tar.gz file https://github.com/canonical/lxd/releases/download/lxd-5.17/lxd-5.17.tar.gz

The other one is github auto generated.

**Comment by geaaru** [comment]
Yeah, sorry, The vendors are present on the release tarball but there is something changed. I'm receiving issue on linking phase about raft:
```
# github.com/canonical/lxd/lxd-migrate
/usr/lib/go/pkg/tool/linux_amd64/link: running x86_64-pc-linux-gnu-gcc failed: exit status 1
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_calloc'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_add'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_state'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_set_heartbeat_timeout'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_last_index'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_errmsg'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_free'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_apply'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_set_pre_vote'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_configuration_add'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_remove'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_bootstrap'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_recover'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_close'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_init'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_uv_set_block_size'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_configuration_init'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_leader'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_uv_close'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_set_max_catch_up_rounds'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_set_max_catch_up_round_duration'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_configuration_close'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_digest'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_set_snapshot_threshold'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_malloc'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_assign'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_barrier'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_uv_set_auto_recovery'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_last_applied'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_set_snapshot_trailing'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_start'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_strerror'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_set_election_timeout'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_uv_init'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.17/work/lxd-5.17/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_transfer'
collect2: error: ld returned 1 exit status
```

Just to share a reference to the ebuild used: I just renamed this: https://github.com/geaaru/geaaru_overlay/blob/funtoo/app-emulation/lxd/lxd-5.16.ebuild in 5.17.

I'm investigating... thanks for the fast feedback

**Comment by geaaru** [comment]
Add more info, tested the tarball from canonical release for LXD 5.15 and I have the same issue.
I'm not sure about this, but it seems that there are differences between the canonical release tarball and the tarball from linuxcontainer.org that is no longer available for comparison.

**Comment by geaaru** [comment]
Could be related to a change from LXC 5.0.2 to 5.0.3 ? (current release in macaroni of LXC is 5.0.2)

**Comment by geaaru** [comment]
Same issue about idmapSet upgrading LXC to version 5.0.3

**Comment by geaaru** [comment]
The issue with idmapSet is correct. This happens because the idmapSet code is CGO only. Disabling it generates that error. So, setting CGO_ENABLE=0 is a bad way. Continue to investigate.

**Comment by tomponline** [comment]
@MusicDin not related specifically to this issue, but I thought I'd ask you here as it is somewhat related:

I think we should update the code tests github workflow:

https://github.com/canonical/lxd/blob/main/.github/workflows/tests.yml#L14

To use `make dist` and then unpack the resulting tarball and then do `make deps` and `make` to test that our `make dist` is producing a compilable tarball to catch any regressions in the future.

Please could you work on this for me?

**Comment by geaaru** [comment]
Just to update here. With the release 5.18 I have the same issue:
```
GOROOT_FINAL='$GOROOT' /usr/lib/go/pkg/tool/linux_amd64/link -o $WORK/b001/exe/a.out -importcfg $WORK/b001/importcfg.link -installsuffix shared -buildmode=pie -buildid=h6w_hor7ctA3UfqAv5fy/ZiwNl6yQ7-ctvIsDMIKw/B6ba64R-uPpyj26asI_p/h6w_hor7ctA3UfqAv5fy -extld=x86_64-pc-linux-gnu-gcc $WORK/b001/_pkg_.a
# github.com/canonical/lxd/lxd-migrate
/usr/lib/go/pkg/tool/linux_amd64/link: running x86_64-pc-linux-gnu-gcc failed: exit status 1
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.18/work/lxd-5.18/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_calloc'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.18/work/lxd-5.18/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_add'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.18/work/lxd-5.18/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_state'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.18/work/lxd-5.18/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_set_heartbeat_timeout'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.18/work/lxd-5.18/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_last_index'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.18/work/lxd-5.18/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_errmsg'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/app-emulation/lxd-5.18/work/lxd-5.18/vendor/dqlite/.libs//libdqlite.so: undefined reference to `raft_free'
```
I had few time to investigate on it. I will try in the next weeks.

**Comment by geaaru** [comment]
This the link to the ebuild used for generate this issue: https://github.com/geaaru/geaaru_overlay/blob/funtoo/app-emulation/lxd/lxd-5.16.ebuild
(just rename it for the different version).

**Comment by geaaru** [comment]
I can now compile `lxd-migrate` forcing `CGO_ENABLED=0` and `-buildmode=pie` but it seems not possible to fix this on `lxc-to-lxd` binary (that requires CGO_ENABLED=1). FWIS the binary `lxc-to-lxd` is not compiled at the moment from your pipeline. Can you confirm that from your side lxc-to-lxd compiles correctly?

**Comment by tomponline** [comment]
> FWIS the binary `lxc-to-lxd` is not compiled at the moment from your pipeline.

Could you explain what you mean by that?

I can see its being built as part of our CI tests, e.g. from the latest build log:

https://pipelinesghubeus23.actions.githubusercontent.com/cCwxTzMg0H8pp8iCgaDG0UDVDkjPRxlZOgQ16ov3uT2bclPUXH/_apis/pipelines/1/runs/29446/signedlogcontent/23?urlExpires=2023-09-25T07%3A44%3A37.1498880Z&urlSigningMethod=HMACV1&urlSignature=0Wl6a5KCWdC1MSAnRYNg57qOfSraZ%2B11s0CxkrFeEyA%3D

I can see its mentioned during the `make` run:

```
2023-09-24T14:29:26.9472949Z github.com/canonical/lxd/lxc-to-lxd
```

**Comment by geaaru** [comment]
Sorry, the URL seems expired. By the way FWIS (maybe I'm in fault), there isn't a target in the Makefile for `lxc-to-lxd`

**Comment by tomponline** [comment]
Its covered by "make"

**Comment by geaaru** [comment]
Hey, just to update here. I think to have the cause:
```
$  ldd /var/tmp/portage/app-emulation/lxd-5.18/work/lxd-5.18/vendor/dqlite/.libs//libdqlite.so
	linux-vdso.so.1 (0x00007ffe06761000)
	libuv.so.1 => /usr/lib64/libuv.so.1 (0x00007f9545cba000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f9545cb5000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9545c95000)
	libsqlite3.so.0 => /usr/lib64/libsqlite3.so.0 (0x00007f9545b3b000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f9545981000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9545d96000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f954583e000)
	libicui18n.so.67 => /usr/lib64/libicui18n.so.67 (0x00007f9545400000)
	libicuuc.so.67 => /usr/lib64/libicuuc.so.67 (0x00007f9545225000)
	libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/libstdc++.so.6 (0x00007f9545043000)
	libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/libgcc_s.so.1 (0x00007f9545822000)
	libicudata.so.67 => /usr/lib64/libicudata.so.67 (0x00007f9543400000)
```
It seems that the libdqlite.so is not linked to raft library. I'm just understanding why this happens.

**Comment by geaaru** [comment]
Now it works.
https://github.com/geaaru/geaaru_overlay/blob/funtoo/app-emulation/lxd/lxd-5.18.ebuild#L119
Fixed with `-lraft` on LDFLAGS. Probably on version until 5.14 the configure of libdsqlite automatically found the `-lraft` option on the configure phase and also when it was missing the link phase was correct.

**Comment by geaaru** [comment]
Thanks for support
